1. Creating Arrays using numpy and accessing their elements and finding their attributes

In [1]:
import numpy as np
#Creating a 1D Array
arr1D = np.array([10,20,30,40,50], dtype = 'float32')
print('1D Array created using numpy')
print('='*40)
print(f'{arr1D}\n')
print('Third element of the array is :',arr1D[2])
print('Fifth element of the array is :',arr1D[4])
print('First element of the array is :',f'{arr1D[0]}\n')
print('Shape of the created 1D array is : ',f'{arr1D.shape}\n')
print('Size of the created 1D array is : ',f'{arr1D.size}\n')
print('Number of dimension in the created 1D array is : ',f'{arr1D.ndim}\n')
print('Type of the created 1D array is : ',f'{type(arr1D)}\n')
print('Datatype of the created 1D array is :',f'{arr1D.dtype}\n')

1D Array created using numpy
[10. 20. 30. 40. 50.]

Third element of the array is : 30.0
Fifth element of the array is : 50.0
First element of the array is : 10.0

Shape of the created 1D array is :  (5,)

Size of the created 1D array is :  5

Number of dimension in the created 1D array is :  1

Type of the created 1D array is :  <class 'numpy.ndarray'>

Datatype of the created 1D array is : float32



In [22]:
#Creating a 2D Array
arr2D = np.array([[1,'3',5],[2,4,9]])
print('2D Array created using numpy')
print('='*40)
print(f'{arr2D}\n')
print('Element in first row and first column is :',arr2D[1,1])
print('Element in Zero row and Second column is :',arr2D[0,2])
print('Element in first row and Second column is :',f'{arr2D[1,2]}\n')
print('Shape of the created 2D array is : ',f'{arr2D.shape}\n')
print('Size of the created 2D array is : ',f'{arr2D.size}\n')
print('Number of dimension in the created 2D array is : ',f'{arr2D.ndim}\n')
print('Type of the created 2D array is : ',f'{type(arr2D)}\n')
print('Datatype of the created 2D array is :',f'{arr2D.dtype}\n')

2D Array created using numpy
[['1' '3' '5']
 ['2' '4' '9']]

Element in first row and first column is : 4
Element in Zero row and Second column is : 5
Element in first row and Second column is : 9

Shape of the created 2D array is :  (2, 3)

Size of the created 2D array is :  6

Number of dimension in the created 2D array is :  2

Type of the created 2D array is :  <class 'numpy.ndarray'>

Datatype of the created 2D array is : <U21



In [3]:
#Creating a 3D Array
arr3D = np.array([[[1,3,5],[2,4,6]] , [[3,6,9],[2,6,8]] , [[9,12,15],[12,14,16]]])
print('3D Array created using numpy')
print('='*40)
print(f'{arr3D}\n')
print('Element in first row and Second column in matrix zero is :',arr3D[0,1,2])
print('Element in first row and Second column in matrix one is :',arr3D[1,1,2])
print('Element in first row and Second column in matrix two is :',f'{arr3D[2,1,2]}\n')
print('Shape of the created 3D array is : ',f'{arr3D.shape}\n')
print('Size of the created 3D array is : ',f'{arr3D.size}\n')
print('Number of dimension in the created 3D array is : ',f'{arr3D.ndim}\n')
print('Type of the created 3D array is : ',f'{type(arr3D)}\n')
print('Datatype of the given 3D array is : 'f'{arr3D.dtype}\n')

3D Array created using numpy
[[[ 1  3  5]
  [ 2  4  6]]

 [[ 3  6  9]
  [ 2  6  8]]

 [[ 9 12 15]
  [12 14 16]]]

Element in first row and Second column in matrix zero is : 6
Element in first row and Second column in matrix one is : 8
Element in first row and Second column in matrix two is : 16

Shape of the created 3D array is :  (3, 2, 3)

Size of the created 3D array is :  18

Number of dimension in the created 3D array is :  3

Type of the created 3D array is :  <class 'numpy.ndarray'>

Datatype of the given 3D array is : int64



2.Creating a new 2D array and slicing their elements row wise and column wise

In [4]:
import numpy as np
years = np.array([[2000,2001,2002,2003],[2004,2005,2006,2007],[2008,2009,2010,2011],[2012,2013,2014,2015]])
print('Years in a 4x4 numpy array is')
print('='*40)
print(f'{years}\n')

Years in a 4x4 numpy array is
[[2000 2001 2002 2003]
 [2004 2005 2006 2007]
 [2008 2009 2010 2011]
 [2012 2013 2014 2015]]



In [5]:
print('Original year array')
print('='*40)
print(f'{years}\n')
print('==> Years in third row index is : 'f'{years[3:]}\n')
print('==> All years till second row index is :\n',f'{years[:3]}\n')
print('==> Years in third column index is : 'f'{years[:,3]}\n')
print('==> All years till second column index is :\n',f'{years[:,0:3]}\n')
print('==> Years in the middle of the second row is : 'f'{years[2,1:3]}\n')
print('==> Years in the middle of the first and second row is :\n 'f'{years[1:3,1:3]}\n')

Original year array
[[2000 2001 2002 2003]
 [2004 2005 2006 2007]
 [2008 2009 2010 2011]
 [2012 2013 2014 2015]]

==> Years in third row index is : [[2012 2013 2014 2015]]

==> All years till second row index is :
 [[2000 2001 2002 2003]
 [2004 2005 2006 2007]
 [2008 2009 2010 2011]]

==> Years in third column index is : [2003 2007 2011 2015]

==> All years till second column index is :
 [[2000 2001 2002]
 [2004 2005 2006]
 [2008 2009 2010]
 [2012 2013 2014]]

==> Years in the middle of the second row is : [2009 2010]

==> Years in the middle of the first and second row is :
 [[2005 2006]
 [2009 2010]]



3.Converting arrays 2D to 1D and 1D to 2D

In [7]:
#Method 1:-Reshape
arr = np.array([2000,2004,2008,2012,2016,2020])
print('Series of years : 'f'{arr}\n')
leap_years = arr.reshape(2,3)
print('After Reshaping the series will look like')
print('='*40)
print(f'{leap_years}\n')

Series of years : [2000 2004 2008 2012 2016 2020]

After Reshaping the series will look like
[[2000 2004 2008]
 [2012 2016 2020]]



In [8]:
#Method 2:-Flatten
arr1 = np.array([[2000,2001,2002,2003],[2004,2005,2006,2007],[2008,2009,2010,2011],[2012,2013,2014,2015]])
print('Table will look like :\n',f'{arr1}\n')
year_series = arr1.flatten()
year_series[0]=1990
print('After flattening table the result will be')
print('='*40)
print(f'{year_series}\n')
print(f'{arr1}\n')

#Note:- flatten will not affect the original array it creates a copy of an array and returns it so original will not be affected

Table will look like :
 [[2000 2001 2002 2003]
 [2004 2005 2006 2007]
 [2008 2009 2010 2011]
 [2012 2013 2014 2015]]

After flattening table the result will be
[1990 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015]

[[2000 2001 2002 2003]
 [2004 2005 2006 2007]
 [2008 2009 2010 2011]
 [2012 2013 2014 2015]]



In [9]:
#Method 3:-Ravel
arr2 = np.array([[2000,2001,2002,2003],[2004,2005,2006,2007],[2008,2009,2010,2011],[2012,2013,2014,2015]])
print('Table will look like :\n',f'{arr2}\n')
years_series = arr2.ravel()
years_series[0] = 1990
print('After ravel the result will be')
print('='*40)
print(f'{years_series}\n')
print(f'{arr2}\n')

#Note:- Ravel will not create a copy and return, it directly make changes in original that may affect the original

Table will look like :
 [[2000 2001 2002 2003]
 [2004 2005 2006 2007]
 [2008 2009 2010 2011]
 [2012 2013 2014 2015]]

After ravel the result will be
[1990 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015]

[[1990 2001 2002 2003]
 [2004 2005 2006 2007]
 [2008 2009 2010 2011]
 [2012 2013 2014 2015]]



4.Performing various operations in numpy array using Arithmetic operators

In [19]:
a = np.array([2,4,6])
b = np.array([1,4,3])

print('Result after adding two arrays : ',(a+b))
print('Result after subtracting two arrays : ',(a-b))
print('Result after multiplying two arrays : ',(a*b))
print('Result after dividing two arrays : ',(a/b))
print('Result after Integer division of two arrays : ',(a//b))
print('Modulo after dividing two arrays : ',(a%b))
print('Value of a with power of b is : ',(a**b))
print('Finding a is equal to b : ',(a==b))

Result after adding two arrays :  [3 8 9]
Result after subtracting two arrays :  [1 0 3]
Result after multiplying two arrays :  [ 2 16 18]
Result after dividing two arrays :  [2. 1. 2.]
Result after Integer division of two arrays :  [2 1 2]
Modulo after dividing two arrays :  [0 0 0]
Value of a with power of b is :  [  2 256 216]
Finding a is equal to b :  [False  True False]


5.Broadcasting

In [21]:
car_price = np.array([[1700000,2000000,2400000],[1800000,2300000,2500000]])
offer_price = np.array([50000,100000,70000])
print('Original price of car is')
print('='*40)
print(f'{car_price}\n')
print('Offer price on Diwali is')
print('='*40)
print(f'{offer_price}\n')
print('Final onroad price of car is')
print('='*40)
print(f'{car_price - offer_price}\n')

Original price of car is
[[1700000 2000000 2400000]
 [1800000 2300000 2500000]]

Offer price on Diwali is
[ 50000 100000  70000]

Final onroad price of car is
[[1650000 1900000 2330000]
 [1750000 2200000 2430000]]



6.Aggregate functions on numpy array

In [34]:
car_price = np.array([[1700000,2000000,2400000],[1800000,2300000,2500000]])
print('Original price of car is')
print('='*40)
print(f'{car_price}\n')
print('Result after using aggregate functions')
print('='*40)
print('Total value of all cars : ',car_price.sum())
print('Mean value of cars : ',car_price.mean())
print('Median value of cars : ',np.median(car_price))
print('Max value of cars : ',car_price.max())
print('Min value of cars : ',car_price.min())
print('Standard variation is : ',car_price.std())
print('Price variance is : ',car_price.var())
print('Sum of prices in rows : ' ,car_price.sum(axis=1))
print('Sum of prices in columns : ' ,car_price.sum(axis=0))

Original price of car is
[[1700000 2000000 2400000]
 [1800000 2300000 2500000]]

Result after using aggregate functions
Total value of all cars :  12700000
Mean value of cars :  2116666.6666666665
Median value of cars :  2150000.0
Max value of cars :  2500000
Min value of cars :  1700000
Standard variation is :  302305.95245361753
Price variance is :  91388888888.88887
Sum of prices in rows :  [6100000 6600000]
Sum of prices in columns :  [3500000 4300000 4900000]


7.Matrix operations on numpy array

In [64]:
#Transpose of matrix
mat = np.array([[1,3,5],[2,4,1]])
print('Original matrix')
print('='*40)
print(f'{mat}\n')
mat_trans = mat.transpose()
print('Transpose matrix')
print('='*40)
print(f'{mat_trans}\n')

Original matrix
[[1 3 5]
 [2 4 1]]

Transpose matrix
[[1 2]
 [3 4]
 [5 1]]



In [57]:
#Dot matrix
#Method 1:-Row and column of same size
mat1 = np.array([[1,3,5],[2,4,1],[1,3,5]])
mat2 = np.array([[1,2,3],[3,2,1],[3,2,1]])
print('Original matrix is')
print('='*40)
print(f'{mat1}\n')
print(f'{mat2}\n')
print('Final value after calculating using Dot matrix is')
print('='*50)
print(np.dot(mat1,mat2))

Original matrix is
[[1 3 5]
 [2 4 1]
 [1 3 5]]

[[1 2 3]
 [3 2 1]
 [3 2 1]]

Final value after calculating using Dot matrix is
[[25 18 11]
 [17 14 11]
 [25 18 11]]


In [67]:
#Method 2:-Row and column of different size
mat1 = np.array([[1,3,5],[2,4,1]])
mat2 = np.array([[1,2,3],[3,2,1]])
print('Original matrix is')
print('='*40)
print(f'{mat1}\n')
print(f'{mat2}\n')
print('Final value after calculating using Dot matrix is')
print('='*50)
print(np.dot(mat1,mat2.T))

Original matrix is
[[1 3 5]
 [2 4 1]]

[[1 2 3]
 [3 2 1]]

Final value after calculating using Dot matrix is
[[22 14]
 [13 15]]


8.Sorting operations on numpy array

In [68]:
#Method 1:-Sorting
marks = np.array([90,60,75,88,91])
print('Original list of marks : ' ,f'{marks}\n')
print('Sorted list of marks : ', f'{np.sort(marks)}\n')

Original list of marks :  [90 60 75 88 91]

Sorted list of marks :  [60 75 88 90 91]



In [83]:
#Method 2:-Argsort
marks = np.array([90,60,75,88,91])
print('Original list of marks : ' ,f'{marks}\n')
print('ArgSorted list : ', f'{np.argsort(marks)}\n')
names = np.array(['Harish','Padma','Dev','Shakthi','Dharan'])
print('list of names : ' ,f'{names}\n')
marks_in_order = np.argsort(marks)
print('Sorted list of marks : ', f'{np.sort(marks)}\n')
print('Names sorted using index value of marks : ',names[marks_in_order])

Original list of marks :  [90 60 75 88 91]

ArgSorted list :  [1 2 3 0 4]

list of names :  ['Harish' 'Padma' 'Dev' 'Shakthi' 'Dharan']

Sorted list of marks :  [60 75 88 90 91]

Names sorted using index value of marks :  ['Padma' 'Dev' 'Shakthi' 'Harish' 'Dharan']


In [94]:
#Method 3:-Conditional sort
scores = np.array([20,55,30,70,90])
print('Original values : ' f'{scores}\n')
print('Scores above 50 : ' f'{np.where(scores > 50)}\n')
print('Result of exams based on marks')
print('='*40)
print(f'{scores}\n')
print(f'{np.where(scores > 50 ,'PASS','FAIL')}\n')

Original values : [20 55 30 70 90]

Scores above 50 : (array([1, 3, 4]),)

Result of exams based on marks
[20 55 30 70 90]

['FAIL' 'PASS' 'FAIL' 'PASS' 'PASS']



9.Concatenating numpy arrays

In [103]:
#Method 1:-Concatenate on rows
mat1 = np.array([[1,3,5],[2,4,1]])
mat2 = np.array([[1,2,3],[3,2,1]])
print('Concatenating on rows')
print('='*40)
print(f'{np.concatenate([mat1,mat2])}\n')

#Method 2:-Concatenate on columns
mat1 = np.array([[1,3,5],[2,4,1]])
mat2 = np.array([[1,2,3],[3,2,1]])
print('Concatenating on columns')
print('='*40)
print(f'{np.concatenate([mat1,mat2],axis=1)}\n')


Concatenating on rows
[[1 3 5]
 [2 4 1]
 [1 2 3]
 [3 2 1]]

Concatenating on columns
[[1 3 5 1 2 3]
 [2 4 1 3 2 1]]

